name: Deploy challenge to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure Google Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        version: 'latest'
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        export_default_credentials: true

    - name: Build and Push Docker image
      env:
        PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        IMAGE: gcr.io/${{ secrets.GCP_PROJECT_ID }}/your-image-name
        DOCKERFILE: Dockerfile
      run: |
        docker build -t $IMAGE -f $DOCKERFILE .
        docker push $IMAGE

    - name: Deploy to GKE
      env:
        PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        CLUSTER_NAME: ${{ secrets.GCP_CLUSTER_NAME }}
        ZONE: ${{ secrets.GCP_CLUSTER_ZONE }}
        IMAGE: gcr.io/${{ secrets.GCP_PROJECT_ID }}/backend
      run: |
        gcloud container clusters get-credentials $CLUSTER_NAME --zone $ZONE --project $PROJECT_ID
        kubectl set image deployment/your-deployment-name your-container-name=$IMAGE